### PR TITLE
Fix front end axios error

### PR DESCRIPTION
**Pull request by T1-O**
Fixes: https://github.com/ordinalsbot/ordinalsbot-node/issues/74

### CODE REVIEW

**Comment by T1-O** [comment]
@SamuelAl We made a small change to the L402 implementation, wondering if you can do a smoke test to make sure its not broken anything?

**Comment by SamuelAl** [comment]
will do, will share results by tomorrow.

**Comment by SamuelAl** [comment]
@T1-O Everything seems to be working fine. Sorry for the delay, been super busy with our Sparkhub launch this week.

**Comment by T1-O** [comment]
> @T1-O Everything seems to be working fine. Sorry for the delay, been super busy with our Sparkhub launch this week.
Perfect, thanks for checking 👍

**Pull request merged**
